name: local_note_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  geolocator: ^9.0.2
  latlong2: ^0.9.1
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  toastification: ^2.3.0
  twilio_flutter: ^0.9.0
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+10
  location: ^6.0.2
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
